spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: service1
        uri: http://localhost:8960
        predicates:
        - Path=/bff_app/v1/*
  zipkin:
    base-url: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}